workflows:
  build:
    name: Build
    max_build_duration: 120
    environment:
      java: openjdk@17
    scripts:
      - name: Install dependencies and build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease


